services:
    postgres:
        image: postgres:17.2
        container_name: TO--postgresql--17.2--5432
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: task_management
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
