version: '3.8'

services:
    db:
        image: postgres:16
        container_name: my_postgres
        restart: always
        env_file:
            - .env
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
        driver: local
